### PR TITLE
Add Throwable to dependencies (prevents installation)

### PR DESCRIPTION
**Pull request by pplu**
Hi,

   Just looks like a missing dependency :smile: 

   Would you be interested in me converting the module to use Dist::Zilla? The way I know to convert it, you would win:
  - deps in a cpanfile (with separate runtime, development and testing dependencies): the Makefile.PL would be automatically generated)
  - installing jp.pl as part of the distribution

### CODE REVIEW

**Comment by rpcme** [comment]
People have been trying to get me to learn Dist::Zilla for quite some time.  I like to control Makefile.PL (you can see I changed it up a bit) and I'm unsure what else needs to change to accompany it.

Since we crossed changes in flight I am just going to post the change, when I get through cleaning all the PBP stuff I would be happy to entertain it.

**Comment by Grinnz** [comment]
You can control the generated Makefile.PL quite extensively by using the [MakeMaker::Awesome] plugin in place of [MakeMaker] (https://metacpan.org/pod/Dist::Zilla::Plugin::MakeMaker::Awesome). All of the META_MERGE stuff can be set directly as metadata with various plugins, that doesn't need to go in the generated Makefile.PL at all (since the META files are not generated by Makefile.PL when using dzil). (If you want any help or tips feel free to stop by #distzilla on irc.perl.org.) By the way (a bit off topic) but you should not set INSTALLDIRS in Makefile.PL since this is not a dual-life core module.

**Comment by pplu** [comment]
OK. I'll create a branch that gives you the base for Dist::Zilla to get you up to speed

**Comment by pplu** [comment]
Also: closing this pull request, as the issue it was reporting is already solved in master (add Throwable as a dependency)

**Comment by rpcme** [comment]
@Grinnz yes, good call - a copy/paste intrusion from File::Path, which is a core module.  I think this deserves an issue

**Pull request closed without merging**
