### PR TITLE
Feature/moose objects

### PR DESCRIPTION
**Pull request by pplu**
Just wanted to write a test that tries out what happens when objects are found inside a datastructure. I think that Jmespath should be able to treat this, but I wanted your opinion before trying to implement it (which seems fairly simple).

Right now Jmespath is just reaching into the internals of the object, treating it as a hash, violating encapsulation. I would opt for making the "key access" to an object call the method on the object. This would help Jmespath call accessors on objects, which are really just methods with no parameters.

What's your opinion?

### CODE REVIEW

**Comment by rpcme** [comment]
Well, the structure is just that - what's being evaluated.  It's not an object in its own right. Yet, if there's blessed objects in the structure, it should implement the TO_JSON hook (see Jmespath::String) for JSON encoding purposes.

Is there something specific we need for Paws here?  I would like to learn the case for it.

Besides that, I am really only concerned about speed.

**Comment by rpcme** [comment]
After thinking about this overnight, perhaps the better thing is to have something like a SearchResult module that does the encapsulation.  I need to think about the semantics.  Because there is need to evaluate blessed objects, I don't want to force the person writing the client to think about what JSON options to use.  When doing so, I think we can remove the evaluate() sub.  Thoughts?

**Comment by pplu** [comment]
> When doing so, I think we can remove the evaluate() sub. Thoughts?

For me, Jmespath is not (only) a JSON crawler / transformer: It's a datastructure crawler / transformer (I really think of JSON documents as serialized datastructures). It helps me extract the parts I find interesting in a datastructure in a "declarative" manner. So what I'm looking for with the "evaluate" sub is: datastructure goes in, datastructure comes out, because I'll want to manipulate it later. Evaluate lets me not have to decode the JSON from the search() sub.

evaluate() lets you be flexible with where the datastructures come from: JSON, YAML, Storable, Sereal...
search() is a great helper for "I want JSON output" (which doesn't support blessed objects, for example)

When you think of it as a datastructure crawler, you get a new case: What happens when you have an object inside your datastructure. And If you have an object that is a datastructure? (a Tree object, for example). I think that treating objects while crawling the datastructure is just adding the following for key access: If the reference I'm seeing is a blessed thing, then use the key as method call, if not, access as a hashref. This would basically avoid lurking into the internals of objects, and letting accessors do their stuff.

**Comment by pplu** [comment]
Hi,

I've implemented the "visit_field" with objects. I've opted for putting Ref::Util into dependencies, as it should be faster than Scalar::Util

**Pull request merged**
